version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
python:
  install:
    - requirements: requirements-website.txt
sphinx:
  configuration: conf.py
formats:
  - epub
  - pdf
