name: Build HTML pages and check links
on:
  push:
  pull_request:
  schedule:
    - cron: "11 11 11 * *"
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pandoc
        run: |
          sudo apt-get install pandoc
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install RTD requirements
        run: |
          python -m pip install -r .readthedocs_requirements.txt
      - name: Build HTML
        run: |
          python -m sphinx -W --keep-going --color -d _build/doctrees/ . _build/html/ -b html
      - name: Check links
        run: |
          python -m sphinx -W --keep-going --color -d _build/doctrees/ . _build/linkcheck/ -b linkcheck -q
      - name: Upload results
        uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: linkcheck
          path: _build/linkcheck/output.*

